#!/bin/bash
#This script illustrates how command-line arguments are counted.
echo Running inputtest2
echo Inputtest2 was invoked with $# command-line arguments.
if [ $# -ge 2 ]; then
  echo the second argument is $2. # 2 is the variable name for the second arg.
else
  echo There are fewer than two arguments.
fi
